### ISSUE TITLE
Document relation to ectaart.cls

### ISSUE THREAD

**Issue by scottkosty** [vtex-soft/texsupport.econometricsociety-ecta#1]
First, thanks so much for maintaining and developing these files! And thanks for moving the development to GitHub so that we can follow the development and maybe even help (e.g., with a bisect if there is a regression).

Do you think it would be helpful to document the relationship of econsocart.cls to ectaart.cls? From what I understand, econsocart.cls is intended to replace ectaart.cls and you suggest authors to move to using econsocart.cls? I think that several readers might have this similar question so it might be nice to put it in the README.md.

I also find it slightly confusing that "ecta" is part of this repository name and I think it is meant as a short name for "Econometrica", but from what I understand econsocart.cls is meant to use also with the journals "Quantitative Economics" and "Theoretical Economics". Similarly, in the README.md only econometrica is mentioned.

My apologies if I jumped the gun on this issue. You just started the repository to maybe you were already planning to address the above.

**Comment by edgaras-sakuras** [comment]
Hi,

thanks for comments!

Yep, this repo is only in its early stage. I'll try to add some info. Stay tuned!

**Comment by scottkosty** [comment]
Sounds good, I'll be patient :) Thanks!

**Comment by edgaras-sakuras** [comment]
Reopening this, typo in the last commit...

**Comment by edgaras-sakuras** [comment]
OK, so I've referred other Econometric Society journals QE and TE in README. As there is a short sentence stating `ectaart`  as obsolete.

One can download template archive:

-   with _variable_ zip file name from here: https://github.com/vtex-soft/texsupport.econometricsociety-ecta/zipball/master);
-   or with _constant_ zip file name from here: https://github.com/vtex-soft/texsupport.econometricsociety-ecta/archive/refs/heads/master.zip.

Greetings from :cloud_with_rain:  Kaunas :hand:

**Comment by scottkosty** [comment]
Great, thank you @edgaras-sakuras !
