### ISSUE TITLE
Multiple bibliography items' citations and "et al."

### ISSUE THREAD

**Issue by hack-r** [vtex-soft/texsupport.econometricsociety-ecta#2]
Apologies if this question is out of place or overly ignorant. I've just updated to `econsocart.cls` in the midst of drafting my first submission to Econometrica. I have a semi-large library of relevant citations exported from Zotero to a .bib file that's read into the .tex file with

```
\bibliography{my_bib} 
\bibliographystyle{econometrica}
```

I need to cite multiple bibliography items in-line. The full list of names for each citation is quite long, so I'll need to use et al. for the in-line citation and leave the full list of names for the actual bibliography. Is there a recommended way to accomplish this? 
I see [this Stack Exchange answer](https://tex.stackexchange.com/questions/26575/bibtex-how-to-reduce-long-author-lists-to-firstauthor-et-al) that recommends using a .bst file with the `natbib` class, but I'm not sure if that's compatible with the `econsocart` / Econometrica way of doing things (or if perhaps there's an official `econsocart` .bst file used to achieve it)?

**Comment by edgaras-sakuras** [comment]
Hello,

usage of *natbib* package and some `.bst` for this task is fine.

I'll try to find is there any official `.bst` for this.

**Comment by sebacea** [comment]
@hack-r could you please confirm that by adding `\usepackage{natbib}` and 

```
\bibliography{my_bib} 
\bibliographystyle{econometrica}
```
joint with a `my_bib.bib` file exported from Zotero in the compilation folder, you are able to use automatic references with `\cite{referencekey}`. I am not able to replicate your example. This is what I have as a resulte trying to cite `\cite{hildenbrand_upper_1972}`

```
Package natbib Warning: Citation `hildenbrand_upper_1972' on page 3 undefined o
n input line 187.
```

Thanks!

**Comment by sebacea** [comment]
including [econometrica.bst](http://tug.ctan.org/tex-archive/biblio/bibtex/contrib/economic/econometrica.bst) solved my problem

**Comment by edgaras-sakuras** [comment]
`econometrica.bst` is not related to this class. The original plan was to write a new (more integrated) `bst`, but since it is not in our priority list, this will take some time. 

Anyway, if `econometrica.bst` solves the problem, then go with it. Thanks @sebacea !

**Comment by edgaras-sakuras** [comment]
`ecta-fullname.bst` was added.
