### ISSUE TITLE
Compilation breaks when using accents in the affiliations

### ISSUE THREAD

**Issue by eduardohorta** [vtex-soft/texsupport.econometricsociety-ecta#4]
I downloaded the package files and went straight to compiling the file ecta_sample.tex: all fine!

Now, if I change, say, from `University` to `Univ\'{e}rsity` on line 73 in the same file, the compiler throws an error: it points to the following line in file ecta_sample.aux:
`\csxdef{affiliation@au1}{First Department of the First Author, U
[ecta_sample.log](https://github.com/vtex-soft/texsupport.econometricsociety-ecta/files/10060217/ecta_sample.log)
niv�rsity{} and Second Department of the First Author, University}`

Any insights on how I could resolve this?

**Comment by edgaras-sakuras** [comment]
Hello,

thanks for noticing this! Download the latest package version.
