### ISSUE TITLE
Lose the issue number of the volume of the journal

### ISSUE THREAD

**Issue by Kuan-Lun** [vtex-soft/texsupport.econometricsociety-ecta#5]
Sorry if this question is out of place or too ignorant. Line 13 on page 9 of the file "ecta_sample.pdf" has no the issue number. Also, "ecta-fullname.bst" may not too show this.

**Comment by edgaras-sakuras** [comment]
Thanks for reporting this.  I've asked our production department to clarify the showing rules for an issue number .

**Comment by edgaras-sakuras** [comment]
:heavy_check_mark:  as :checkered_flag:
