### ISSUE TITLE
Bug in year suffixing

### ISSUE THREAD

**Issue by williamliuecon** [vtex-soft/texsupport.econometricsociety-ecta#7]
There seems to be a bug in the year suffixing when there are (at least?) two authors shared between two works and both are not the last authors.

Here is the source code for a minimum working example to reproduce the bug:
[test.zip](https://github.com/vtex-soft/texsupport.econometricsociety-ecta/files/13966208/test.zip)

Here are the contents of the .bib:
```
@article{cite1,
  title        = {Title1},
  author       = {A, NameA and B, NameB and D, NameD and E, NameE},
  year         = {2022},
  journal      = {JournalName},
}
@article{cite2,
  title        = {Title2},
  author       = {A, NameA and C, NameC and D, NameD and F, NameF},
  year         = {2022},
  journal      = {JournalName},
}
```

The years are displayed as "2000a" and "2000b" in the bibliography even though the set of authors differs between the two works. For the bug to occur, the authors B and C can be omitted, but E and F are necessary.

**Comment by lstonys** [comment]
When there are more persons citing label becomes `<first person surname> et al., <year>`  and then you get:
```
A et~al., 2022
A et~al., 2022
```
So extra letters is added to recognize which of the cite refers to which bibliography entry. Without letters in the printed paper you will not know which reference was cited with `A et~al., 2022`.

**Comment by williamliuecon** [comment]
I see. Are you sure that's the correct style? I would have expected that for an in-text citation, if the set of authors is different between two works, enough authors' names to make them distinct would be listed, i.e.,
> A, B, et al. (2022)
A, C, et al. (2022)

rather than
> A et al. (2022a)
A et al. (2022b)

**Comment by lstonys** [comment]
Bibtex style is provided by publisher and many of the bibtex styles act the same forming in-text citation labels. 
If you wish to change it you can add bibliography directly to tex file and edit these labels like:

```
....
\begin{document}
\cite{cite1}
\cite{cite2}

\begin{thebibliography}{2}
\newcommand{\enquote}[1]{``#1''}
\expandafter\ifx\csname natexlab\endcsname\relax\def\natexlab#1{#1}\fi

\bibitem[\protect\citeauthoryear{A, B, D, and E}{A, B, et~al.}{2022{\natexlab{a}}}]{cite1}
\textsc{A, NameA, NameB B, NameD D, and NameE E} (2022{\natexlab{a}}):
  \enquote{Title1,} \emph{JournalName}.

\bibitem[\protect\citeauthoryear{A, C, D, and F}{A, C,  et~al.}{2022{\natexlab{b}}}]{cite2}
\textsc{A, NameA, NameC C, NameD D, and NameF F} (2022{\natexlab{b}}):
  \enquote{Title2,} \emph{JournalName}.

\end{thebibliography}
\end{document}

```
