### ISSUE TITLE
For even pages, there is no right margin 

### ISSUE THREAD

**Issue by Stephville** [vtex-soft/texsupport.econometricsociety-ecta#8]
After compiling the tex file on overleaf, the pdf has no right margin for even pages.

**Comment by edgaras-sakuras** [comment]
Hello,

did you add any additional packages, settings or options in your article? 

I've uploaded sample, cls, cfg, bst and figure files to Overleaf and it compiles (with pdflatex 2022 or 2023) and PDF is shown without any problems.

**Comment by Stephville** [comment]
Hello

Thank for your message.

I think so.



Le jeu. 25 janv. 2024, 11:25, Edgaras Šakuras ***@***.***> a
écrit :

**Comment by edgaras-sakuras** [comment]
Without knowing exact packages loaded, this issue can not be solved.

**Comment by edgaras-sakuras** [comment]
Anyway, the margins are not that important, as they're always reset at the production stage. Just do not alter main font size and text width/height.
